"""Events added

Revision ID: ebab22b8ab62
Revises: 216a1d836e80
Create Date: 2019-11-03 19:17:21.488095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebab22b8ab62'
down_revision = '216a1d836e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('event', sa.Column('venue', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'venue')
    op.drop_column('event', 'name')
    # ### end Alembic commands ###
